/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: DDigi (https://sketchfab.com/DDigi)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/ethereum-logo-6c568bbd6ff4407a82643ce543626b4f
title: Ethereum logo
*/

import React, { useRef } from 'react'
import { OrbitControls, useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/ethereum.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={6}>
        <OrbitControls enableZoom={false} />
        <mesh geometry={nodes.Object_2.geometry} material={materials.material_0} color='#F00000' />
      </group>
    </group>
  )
}

useGLTF.preload('/ethereum.gltf')
